name: AccountServer Build

on:
  push:
    branches: [ "main", "feat/migration-to-console" ]
    paths:
      - XAccountServer/**
      - .github/workflows/accountserver-build.yml

jobs:
  build-docker:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - uses: mr-smithers-excellent/docker-build-push@v5
      name: Build & push Docker image
      with:
        image: mir-eternal/accountserver
        tags: latest
        registry: docker.pkg.github.com
        dockerfile: ./XAccountServer/Dockerfile
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

  build-bin:
    strategy:
      matrix:
        targets: [win10-x86,win10-x64]

    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Install .NET Core
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x

    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v1.0.2

    - name: Build Applications
      run: dotnet publish -c release -r $env:Target --self-contained -o ./publish/$env:Target XAccountServer
      env:
        Target: ${{ matrix.targets }}

    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: XAccountServer-${{env.Target}}
        path: ./publish/${{env.Target}}
      env:
        Target: ${{ matrix.targets }}