name: GameServer Build

on:
  push:
    branches: [ "main", "feat/upgrade-net6" ]
    paths:
      - GameServer/**
      - .github/workflows/gameserver-build.yml

jobs:
  build:
    strategy:
      matrix:
        targets: [win10-x86,win10-x64]

    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Install .NET Core
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x

    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v1.0.2

    - name: Build Applications
      run: dotnet publish -c release -r $env:Target --self-contained -o ./publish/$env:Target GameServer
      env:
        Target: ${{ matrix.targets }}

    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: GameServer-${{Target}}
        path: ./publish/${{Target}}
      env:
        Target: ${{ matrix.targets }}

