name: Build Server Apps

on:
  push:
    branches: [ "main", "feat/upgrade-net6" ]
    paths:
      - AccountServer/**
      - GameServer/**
      - Launcher/**
      - .github/workflows/server-apps.yml

jobs:
  build:
    strategy:
      matrix:
        projects: [GameServer, AccountServer, Launcher]
        targets: [win10-x86,win10-x64]

    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Install .NET Core
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x

    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v1.0.2

    - name: Build Applications
      run: dotnet publish -c release -r $env:Target --self-contained -o ./publish/$env:Target/$env:Project $env:Project
      env:
        Target: ${{ matrix.targets }}
        Project: ${{ matrix.projects }}

    - name: Upload build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: MirEternal
        path: ./publish/

